					-- View Data --
select * from location;
select * from category;
select * from customer;
select * from salesEx;
select * from products;
select * from orderT;
select * from order_product;
select * from se_pro_category;